export { default as Home } from './Home/Home';
export { default as Login } from './Login/Login';
export { default as Register } from './Register/Register';
export { default as Settings } from './Settings/Settings';
export { default as Profile } from './Profile/Profile';
export { default as Test } from './Test/Test';
export { default as FindWork } from './FindWork/FindWork';
export { default as PostJob } from './PostJob/PostJob';
export { default as JobDetail } from './JobDetail/JobDetail';
